spring:
  application:
    name: MiniProgramBackstage

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sport_miniprogram
    username: root
    password: 917874407